config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/home', to: "pages#home"
  get '/projects', to: "pages#projects"
  get '/contact', to: "pages#contact"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Desafio Portafolio</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;1,300&display=swap" rel="stylesheet">
  <link rel="shortcut icon" href="<%= asset_path 'icons/favicon.ico'%>" type="image/x-icon">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>

  <nav class="navbar navbar-expand-lg bg-dark px-5">
    <div class="container-fluid py-2">
      <%= link_to 'Mi portafolio', home_path, class: "navbar-brand text-white ms-5 fw-bold" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-3">
          <%=link_to "Home", home_path, class: "nav-link text-white mx-3"%>
          <%=link_to "Proyectos", projects_path, class: "nav-link text-white mx-3"%>
          <%=link_to "Contacto", contact_path, class: "nav-link text-white mx-3"%>
        </div>
      </div>
    </div>
  </nav>


  <div class="pb-5"><%= yield %></div>

  <footer class="bg-dark">
    <div class="container-fluid row align-items-center">
      <a class="btn my-3" href="https://github.com/kotoykm" role="button" target="_blank"> <i class="fab fa-github fs-1 text-white"></i> </a>
    </div>
    <div class="text-center p-3" id="bottom-footer">
      <span class="text-white">Erick Rivera © 2023</span>
  </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/pages/contact.html.erb
<div class="container pt-5">
    <h1 class="display-4">Contacto</h1>
    <hr>
    <div class="row pb-5 mb-5">
        <div class="col-md-12">
            <form>
                <div class="mb-4">
                    <label for="exampleInputName" class="form-label fs-6">Nombre</label>
                    <input type="text" name="exapleName" id="ExapleInputName" class="form-control"
                        placeholder="Nombre">
                </div>
                <div class="mb-4">
                    <label for="exampleInputEmail1" class="form-label fs-6">Correo Electrónico</label>
                    <input type="email" class="form-control" id="exampleInputEmail1"
                        aria-describedby="emailHelp" placeholder="Correo Electrónico">
                </div>
                <div class="mb-3 d-none d-sm-none d-md-none d-lg-block d-xl-block d-xxl-block">
                    <label for="exampleInputMessage" class="form-label">Mensaje (Opcional)</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="8"
                        placeholder="Escribe aquí tu mensaje"></textarea>
                </div>
                <div class="text-center text-md-start">
                    <button type="submit" class="btn btn-dark px-4 py-2 text-white">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid px-0">
  <div class="card text-white text-shadow mb-5">
      <%= image_tag 'img1.png', class:"card-img" %>
      <div class="card-img-overlay">
          <div class="pe-3">
              <div class="row ps-3 pt-2">
                  <h5 class="card-title display-2 fw-bold">Erick Rivera</h5>
                  <p class="card-text col-3 fs-4">
                      Diseñador multimedia. Actualmente formándome en informática.
                  </p>
              </div>
          </div>
      </div>
  </div>
</div>
<!--------------------------------------------------------------------------------->
<div class="container">
  <div class="row">
      <div class="col-4">
          <div class="card">
              <%= image_tag 'home1.png', class:"card-img-top" %>
              <div class="card-body text-center">
                <%=link_to "Inicio", home_path, class: "btn btn-outline-dark fs-3 px-5"%>
              </div>
            </div>
      </div>
      <div class="col-4">
          <div class="card">
              <%= image_tag 'home2.png', class:"card-img-top" %>
              <div class="card-body text-center">
                <%=link_to "Proyectos", projects_path, class: "btn btn-outline-dark fs-3 px-5"%>
              </div>
            </div>
      </div>
      <div class="col-4">
          <div class="card">
              <%= image_tag 'home3.png', class:"card-img-top" %>
              <div class="card-body text-center">
                <%=link_to "Contacto", contact_path, class: "btn btn-outline-dark fs-3 px-5"%>
              </div>
            </div>
      </div>
  </div>
</div>

app/views/pages/projects.html.erb
<div class="container pt-5">
    <h1 class="display-4">Mis proyectos</h1>
    <hr>
    <div class="row">
        <div class="col-4">
            <div class="card">
                <%= image_tag 'work/work1.jpg', class:"card-img-top" %>
                <div class="card-body">
                    <h4 class="card-title fw-bold">Ricomida</h4>
                    <p class="card-text">Una web responsiva para un restaurante. Utiliza Bootstrap 5 y Popper.js.</p>
                    <%=link_to "Ver más", home_path, class: "btn btn-custom px-4"%>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <%= image_tag 'work/work2.jpg', class:"card-img-top" %>
                <div class="card-body">
                    <h4 class="card-title fw-bold">Viajes Chile</h4>
                    <p class="card-text">Una web responsiva para una agencia de viajes. Utiliza Bootstrap 5 y Jquery</p>
                    <%=link_to "Ver más", home_path, class: "btn btn-custom px-4"%>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <%= image_tag 'work/work3.jpg', class:"card-img-top" %>
                <div class="card-body">
                    <h4 class="card-title fw-bold">Nasa App</h4>
                    <p class="card-text">Una aplicación Ruby on Rails que se conecta a una api para mostrar fotos.</p>
                    <%=link_to "Ver más", home_path, class: "btn btn-custom px-4"%>
                </div>
            </div>
        </div>
    </div>
</div>